#!/usr/bin/env bash
set -u

ROOT_DIR="/workspaces/openclaw-akida-agent-lab"
CONTEXT_FILE="$ROOT_DIR/OPENCLAW_CONTEXT.md"
cd "$ROOT_DIR" || exit 1

sync_openclaw_context() {
  local tmp_context tmp_memory

  tmp_context=$(mktemp)
  {
    echo "# OpenClaw Context"
    echo
    echo "This file is generated by .devcontainer/scripts/bootstrap.sh to preserve durable project context for OpenClaw-style loops."
    echo
    echo "## Source Files"
    echo "- `HighLevelGoasl.md`"
    echo "- `chatHistory.txt`"
    echo

    echo "## High-Level Goal"
    echo
    if [ -f HighLevelGoasl.md ]; then
      cat HighLevelGoasl.md
    else
      echo "Missing source file: HighLevelGoasl.md"
    fi
    echo

    echo "## Chat History"
    echo
    if [ -f chatHistory.txt ]; then
      echo '```text'
      cat chatHistory.txt
      echo '```'
    else
      echo "Missing source file: chatHistory.txt"
    fi
  } > "$tmp_context"
  mv "$tmp_context" "$CONTEXT_FILE"
  echo "[bootstrap] synced OPENCLAW_CONTEXT.md from source files"

  tmp_memory=$(mktemp)
  awk '
    BEGIN {skip=0}
    /^## Persistent Context$/ {skip=1; next}
    skip && /^## / {skip=0}
    !skip {print}
  ' MEMORY.md > "$tmp_memory"
  mv "$tmp_memory" MEMORY.md

  cat >> MEMORY.md <<'MEMORY_CONTEXT_EOF'

## Persistent Context
- Canonical context snapshot: `OPENCLAW_CONTEXT.md`
- Source files synchronized on bootstrap: `HighLevelGoasl.md`, `chatHistory.txt`
- Purpose: keep project goals and prior planning available alongside experiment memory for autonomous loops
MEMORY_CONTEXT_EOF
  echo "[bootstrap] refreshed Persistent Context section in MEMORY.md"
}

echo "[bootstrap] Preparing workspace files..."

if [ ! -f MEMORY.md ]; then
  touch MEMORY.md
  echo "[bootstrap] created MEMORY.md"
fi
if [ ! -f AGENTS.md ]; then
  touch AGENTS.md
  echo "[bootstrap] created AGENTS.md"
fi
if [ ! -f TOOLS.md ]; then
  touch TOOLS.md
  echo "[bootstrap] created TOOLS.md"
fi

if [ ! -s AGENTS.md ]; then
  cat > AGENTS.md <<'AGENT_EOF'
# Agent Role
Senior Neuromorphic Hardware Engineer

# Mission
Build and iteratively improve a spiking-transformer-style attention block on BrainChip Akida tooling.

# Primary Objective
Demonstrate a reproducible energy-efficiency gain target of at least 5x on a transformer attention-like component while keeping quality loss under 1% against a dense FP32 baseline on a small open model.

# Constraints
1. Always run generated code and validate from terminal output.
2. Log every failed attempt and its root cause in MEMORY.md.
3. Prefer sparse activations and report measured sparsity per experiment.
4. When conversion fails, try alternate quantization/conversion paths before abandoning an approach.
5. Keep results reproducible with deterministic seeds and saved config.

# Execution Loop
1. Plan one small experiment.
2. Implement the script or config update.
3. Execute and capture metrics.
4. Write findings and next hypothesis in MEMORY.md.
5. Repeat until objective is met or blockers are clearly documented.
AGENT_EOF
  echo "[bootstrap] seeded AGENTS.md from project high-level goal"
fi

if [ ! -s TOOLS.md ]; then
  cat > TOOLS.md <<'TOOLS_EOF'
# Tooling Notes
- Python: akida, cnn2snn, akida_models
- Runtime: OpenClaw (agent loop)
- Auth: Codex OAuth (device flow) preferred over raw API key

# Standard Checks
- node --version
- npm --version
- python -c "import akida; print(akida.__version__)"
- codex login --device-auth
- codex login status
TOOLS_EOF
  echo "[bootstrap] seeded TOOLS.md"
fi

if [ ! -s MEMORY.md ]; then
  cat > MEMORY.md <<'MEMORY_EOF'
# Experiment Memory

## Format
- Date/Time (UTC)
- Experiment ID
- Hypothesis
- Command(s)
- Result
- Error/Root Cause
- Next Action
MEMORY_EOF
  echo "[bootstrap] seeded MEMORY.md"
fi

sync_openclaw_context

echo "[bootstrap] Validating toolchain..."

if ! command -v node >/dev/null 2>&1 || ! command -v npm >/dev/null 2>&1; then
  echo "[bootstrap] WARN: Node.js/npm not found. Rebuild the container first."
  exit 0
fi

echo "[bootstrap] node: $(node --version)"
echo "[bootstrap] npm:  $(npm --version)"

if command -v codex >/dev/null 2>&1; then
  echo "[bootstrap] codex: $(codex --version)"
else
  echo "[bootstrap] WARN: codex CLI not found in PATH."
  echo "[bootstrap] Install OpenAI ChatGPT extension in Codespaces or provide a codex binary."
fi

if ! command -v openclaw >/dev/null 2>&1; then
  echo "[bootstrap] openclaw not found; trying npm install -g openclaw@latest"
  if npm install -g openclaw@latest; then
    echo "[bootstrap] openclaw installed successfully."
  else
    echo "[bootstrap] WARN: Could not install openclaw automatically."
    echo "[bootstrap] Verify package name/access, then run: npm install -g openclaw@latest"
  fi
else
  echo "[bootstrap] openclaw: $(openclaw --version || echo installed)"
fi

echo "[bootstrap] Setup checks complete."
